version: 1.2
workflows:
  - name: Exercise5_fast
    subclass: WDL
    primaryDescriptorPath: /Exercise5_fast.wdl
  - name: Exercise5_slow
    subclass: WDL
    primaryDescriptorPath: /Exercise5_slow.wdl
