version: 1.2
workflows:
  - name: Exercise5_fast
    subclass: WDL
    primaryDescriptorPath: /Exercise5/HERRO_assembly/Exercise5_fast.wdl
    testParameterFiles:
      - /Exercise5/HERRO_assembly/inputs_HP1.json
  - name: Exercise5_slow
    subclass: WDL
    primaryDescriptorPath: /Exercise5/HERRO_assembly/Exercise5_slow.wdl
    testParameterFiles:
      - /Exercise5/HERRO_assembly/inputs_HP1.json
